name: flutter_portugal_scheduler
description: "A Flutter Portugal Agenda App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dart_mappable: ^4.2.2
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.2.3

flutter:
  uses-material-design: true
  assets: 
    - assets/events.json 
