// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'data.mapper.dart';

/// Any class that is mapped from JSON must extend `JsonMappable`
///
/// This requires the `build_runner` package to be run.
///
@MappableClass()
class Events with EventsMappable {
  final List<Event> events;

  Events({required this.events});
}

@MappableClass()
class Event with EventMappable {
  final String speaker;
  final String description;
  final String title;
  final DateTime time;

  Event({
    required this.speaker,
    required this.description,
    required this.title,
    required this.time,
  });
}
